### ISSUE TITLE
Error in case virtualenv is not used

### ISSUE THREAD

**Issue by philippeowagner** [3bot/3bot-worker#8]
root@dummy:~# worker.py start
    Traceback (most recent call last):
      File "/usr/local/bin/worker.py", line 19, in <module>
        if os.environ['VIRTUAL_ENV']:
      File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
        raise KeyError(key)
    KeyError: 'VIRTUAL_ENV'

**Comment by philippeowagner** [comment]
(invalid)
